function compareEnums(a, b) {
    if (typeof a == "string" && typeof b == "string") {
        a = a.toLowerCase();
        b = b.toLowerCase();
    }
    return a == b || (a && b && a.$id && b.$id && a.$id == b.$id);
}

const ENUM = {}

ENUM.QuerySelector = {
    Equals: {
        $id: 41,
        test(v, ref) {
            return compareEnums(v, ref);
        },
        aliases: ["equals", "=", "is"],
    },
    DoesNotEqual: {
        $id: 49,
        test(v, ref) {
            return !compareEnums(v, ref);
        },
        aliases: ["does not equal", "!=", "is not"],
    },
    GreaterThan: {
        $id: 40,
        test(v, ref) {
            return v > ref;
        },
        aliases: ["is greater than", "greater than", ">"],
    },
    LessThan: {
        $id: 42,
        test(v, ref) {
            return v < ref;
        },
        aliases: ["is less than", "less than", "<"],
    },
    NotGreaterThan: {
        $id: 48,
        test(v, ref) {
            return v <= ref;
        },
        aliases: ["is not greater than", "not greater than", "<="],
    },
    NotLessThan: {
        $id: 42,
        test(v, ref) {
            return v >= ref;
        },
        aliases: ["is not less than", "not less than", ">="],
    },
    Includes: {
        $id: 43,
        test(v, ref) {
            return typeof v == "object" && v.includes(ref);
        },
        aliases: [],
    },
    Excludes: {
        $id: 44,
        test(v, ref) {
            return typeof v != "object" || !v.includes(ref);
        },
        aliases: [],
    },
};

ENUM.QuerySelector.Equals.antiSelector = ENUM.QuerySelector.DoesNotEqual;
ENUM.QuerySelector.DoesNotEqual.antiSelector = ENUM.QuerySelector.Equals;
ENUM.QuerySelector.GreaterThan.antiSelector = ENUM.QuerySelector.NotGreaterThan;
ENUM.QuerySelector.NotGreaterThan.antiSelector = ENUM.QuerySelector.GreaterThan;
ENUM.QuerySelector.LessThan.antiSelector = ENUM.QuerySelector.NotLessThan;
ENUM.QuerySelector.NotLessThan.antiSelector = ENUM.QuerySelector.LessThan;
ENUM.QuerySelector.Includes.antiSelector = ENUM.QuerySelector.Excludes;
ENUM.QuerySelector.Excludes.antiSelector = ENUM.QuerySelector.Includes;

ENUM.Property = {
    AtomicNumber: {
        $id: 21,
        name: "atomic number",
        key: "atomicNumber",
        type: "number",
        aliases: ["atomic number", "number"],
    },
    Name: {
        $id: 22,
        name: "name",
        key: "name",
        type: "string",
        aliases: ["name"],
    },
    Symbol: {
        $id: 23,
        name: "chemical symbol",
        key: "symbol",
        type: "string",
        aliases: ["chemical symbol", "symbol"],
    },
    RoomTempState: {
        $id: 24,
        name: "state at room temperature",
        key: "roomTempState",
        type: ENUM.State,
        aliases: ["room temp state", "room temperature state", "state"],
    },
    Series: {
        $id: 25,
        name: "series",
        key: "series",
        type: ENUM.Series,
        aliases: ["series"],
    },
    Metal: {
        $id: 26,
        name: "metal",
        key: "metal",
        type: ENUM.Metal,
        aliases: ["metal"],
    },
    Families: {
        $id: 27,
        name: "families",
        key: "families",
        type: "object",
        aliases: [],
    },
    AtomicMass: {
        $id: 28,
        name: "atomic mass",
        key: "atomicMass",
        type: "number",
        aliases: ["atomic mass", "mass"],
    },
    Electronegativity: {
        $id: 29,
        name: "electronegativity",
        key: "electronegativity",
        type: "number",
        aliases: ["electronegativity"],
    },
    CalculatedRadius: {
        $id: 30,
        name: "calculated radius",
        key: "calculatedRadius",
        type: "number",
        aliases: ["calculated radius", "radius"],
    },
    ElectronAffinity: {
        $id: 31,
        name: "electron affinity",
        key: "electronAffinity",
        type: "number",
        aliases: ["electron affinity", "affinity"],
    },
    FirstIonization: {
        $id: 32,
        name: "first ionization",
        key: "firstIonization",
        type: "number",
        aliases: ["first ionization"],
    },
    Period: {
        $id: 33,
        name: "period",
        key: "period",
        type: "number",
        aliases: ["period"],
    },
    Group: {
        $id: 34,
        name: "group",
        key: "group",
        type: ENUM.Group,
        aliases: ["group"],
    },
    GroupNum: {
        $id: 47,
        name: "group number",
        key: "groupNum",
        type: "number",
        aliases: [],
    },
    Block: {
        $id: 35,
        name: "block",
        key: "block",
        type: ENUM.Block,
        aliases: ["block"],
    }
};

ENUM.Block =  {
    S: {
        $id: 36,
        name: "s block",
        aliases: ["s block"],
    },
    P: {
        $id: 37,
        name: "p block",
        aliases: ["p block"],
    },
    D: {
        $id: 38,
        name: "d block",
        aliases: ["d block"],
    },
    F: {
        $id: 39,
        name: "f block",
        aliases: ["f block"],
    }
};

ENUM.State = {
    Solid: { $id: 1, singular: "a solid", class: "solid", aliases: ["solid"] },
    Liquid: { $id: 2, singular: "a liquid", class: "liquid", aliases: ["liquid"] },
    Gas: { $id: 3, singular: "a gas", class: "gas", aliases: ["gas"] },
    Unknown: { $id: 20, singular: "in an unknown state", class: "unknown-state", aliases: ["unknown state", "unknown"] },
};

ENUM.Series = {
    AlkaliMetals: {
        $id: 4,
        name: "Alkali Metals",
        singular: "an alkali metal",
        class: "alkali-metal",
        aliases: ["alkali metal", "alkali"],
    },
    AlkalineEarthMetals: {
        $id: 5,
        name: "Alkaline Earth Metals",
        singular: "an alkaline earth metal",
        class: "alkaline-earth-metal",
        aliases: ["alkaline earth metal", "alkaline earth", "alkaline"],
    },
    Lanthanoids: {
        $id: 6,
        name: "Lanthanoids",
        singular: "a lanthanoid",
        class: "lanthanoid",
        aliases: ["lanthanoid", "lanthanide"],
    },
    Actinoids: {
        $id: 7,
        name: "Actinoids",
        singular: "an actinoid",
        class: "actinoid",
        aliases: ["actinoid", "actinide"],
    },
    TransitionMetals: {
        $id: 8,
        name: "Transition Metals",
        singular: "a transition metal",
        class: "transition-metal",
        aliases: ["transition metal", "transition"],
    },
    PostTransitionMetals: {
        $id: 9,
        name: "Post-Transition Metals",
        singular: "a post-transition metal",
        class: "post-transition-metal",
        aliases: ["post transition metal", "post-transition metal", "post-transition", "post transition"],
    },
    Metalloids: {
        $id: 10,
        name: "Metalloids",
        singular: "a metalloid",
        class: "metalloid",
        aliases: ["metalloid"],
    },
    ReactiveNonmetals: {
        $id: 11,
        name: "Reactive Nonmetals",
        singular: "a reactive nonmetal",
        class: "reactive-nonmetal",
        aliases: ["reactive nonmetal", "reactive non-metal"],
    },
    NobleGases: {
        $id: 12,
        name: "Noble Gases",
        singular: "a noble gas",
        class: "noble-gas",
        aliases: ["noble gas", "noble"],
    },
};

ENUM.Metal = {
    Nonmetal: { $id: 13, singular: "a nonmetal", aliases: ["nonmetal", "non-metal"] },
    Metalloid: { $id: 10, singular: "a metalloid", aliases: ["metalloid"] },
    Metal: { $id: 14, singular: "a metal", aliases: ["metal"] },
};

ENUM.Family = {
    Radioactive: {
        $id: 45,
        posDesc: "has no stable isotopes",
        negDesc: "has one or more stable isotopes",
        class: "radioactive",
        aliases: ["radioactive", "no stable isotopes", "not stable", "unstable"]
    },
    Synthetic: {
        $id: 46,
        posDesc: "is synthetic and created by humans",
        negDesc: "is not synthetic",
        class: "synthetic",
        aliases: ["synthetic", "man made", "man-made"]
    }
}

ENUM.Group = {
    AlkaliMetals: {
        $id: 4,
        groups: [1],
        charge: 1,
        singular: "an alkali metal",
        class: "alkali-metal",
        aliases: [], // already defined in the series, shouldn't affect search
    },
    AlkalineEarthMetals: {
        $id: 5,
        groups: [2],
        charge: 2,
        singular: "an alkaline earth metal",
        class: "alkaline-earth-metal",
        aliases: [],
    },
    Transition: {
        $id: 8,
        groups: [3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        singular: "a transition metal",
        class: "transition-metal",
        aliases: [],
    },
    Triels: {
        $id: 15,
        groups: [13],
        singular: "a triel",
        class: "triel",
        aliases: ["triel", "boron group"],
    },
    Tetrels: {
        $id: 16,
        groups: [14],
        singular: "a tetrel",
        class: "tetrel",
        aliases: ["tetrel", "carbon group"],
    },
    Pnictogens: {
        $id: 17,
        groups: [15],
        charge: -3,
        singular: "a pnictogen",
        class: "pnictogen",
        aliases: ["pnictogen", "nitrogen group"],
    },
    Chalcogens: {
        $id: 18,
        groups: [16],
        charge: -2,
        singular: "a chalcogen",
        class: "chalcogen",
        aliases: ["chalcogen", "oxygen group"],
    },
    Halogens: {
        $id: 19,
        groups: [17],
        charge: -1,
        singular: "a halogen",
        class: "halogen",
        aliases: ["halogen", "fluorine group"],
    },
    NobleGasses: {
        $id: 12,
        groups: [18],
        charge: 0,
        singular: "a noble gas",
        class: "noble-gas",
        aliases: ["helium group", "neon group"],
    },
    Lanthanoids: {
        $id: 6,
        groups: [],
        singular: "a lanthanoid",
        class: "lanthanoid",
        aliases: [],
    },
    Actinoids: {
        $id: 7,
        groups: [],
        singular: "an actinoid",
        class: "actinoid",
        aliases: [],
    },
};

// ENUM.Element = { $id: 16 }

// assume room temperature conditions (25 deg C)
// radius is in pm (picometers)
// atomicMass is in u (atomic mass units)
// electronAffinity is in kJ/mol
// firstIonization is in kJ/mol
// electronegativity uses Pauling scale
const elements = [
    {
        atomicNumber: 1,
        name: "Hydrogen",
        symbol: "H",
        roomTempState: ENUM.State.Gas,
        series: ENUM.Series.ReactiveNonmetals,
        metal: ENUM.Metal.Nonmetal,
        group: null,
        families: [],
        atomicMass: 1.008,
        electronegativity: 2.2,
        calculatedRadius: 53,
        electronAffinity: 72.8,
        firstIonization: 1312.0,
        period: 1,
        groupNum: 1,
        block: ENUM.Block.S,
    },
    {
        atomicNumber: 2,
        name: "Helium",
        symbol: "He",
        roomTempState: ENUM.State.Gas,
        series: ENUM.Series.NobleGases,
        metal: ENUM.Metal.Nonmetal,
        group: ENUM.Group.NobleGasses,
        families: [],
        atomicMass: 4.003,
        electronegativity: null,
        calculatedRadius: 31,
        electronAffinity: null,
        firstIonization: 2372.3,
        period: 1,
        groupNum: 18,
        block: ENUM.Block.S,
    },
    {
        atomicNumber: 3,
        name: "Lithium",
        symbol: "Li",
        roomTempState: ENUM.State.Solid,
        series: ENUM.Series.AlkaliMetals,
        metal: ENUM.Metal.Metal,
        group: ENUM.Group.AlkaliMetals,
        families: [],
        atomicMass: 6.941,
        electronegativity: 0.98,
        calculatedRadius: 167,
        electronAffinity: 59.6,
        firstIonization: 520.2,
        period: 2,
        groupNum: 1,
        block: ENUM.Block.S,
    },
    {
        atomicNumber: 4,
        name: "Beryllium",
        symbol: "Be",
        roomTempState: ENUM.State.Solid,
        series: ENUM.Series.AlkalineEarthMetals,
        metal: ENUM.Metal.Metal,
        group: ENUM.Group.AlkalineEarthMetals,
        families: [],
        atomicMass: 9.012,
        electronegativity: 1.57,
        calculatedRadius: 112,
        electronAffinity: null,
        firstIonization: 899.5,
        period: 2,
        groupNum: 2,
        block: ENUM.Block.S,
    },
    {
        atomicNumber: 5,
        name: "Boron",
        symbol: "B",
        roomTempState: ENUM.State.Solid,
        series: ENUM.Series.Metalloids,
        metal: ENUM.Metal.Metalloid,
        group: ENUM.Group.Triels,
        families: [],
        atomicMass: 10.811,
        electronegativity: 2.04,
        calculatedRadius: 87,
        electronAffinity: 26.7,
        firstIonization: 800.6,
        period: 2,
        groupNum: 13,
        block: ENUM.Block.P,
    },
    {
        atomicNumber: 6,
        name: "Carbon",
        symbol: "C",
        roomTempState: ENUM.State.Solid,
        series: ENUM.Series.ReactiveNonmetals,
        metal: ENUM.Metal.Nonmetal,
        group: ENUM.Group.Tetrels,
        families: [],
        atomicMass: 12.011,
        electronegativity: 2.55,
        calculatedRadius: 67,
        electronAffinity: 153.9,
        firstIonization: 1086.5,
        period: 2,
        groupNum: 14,
        block: ENUM.Block.P,
    },
    {
        atomicNumber: 7,
        name: "Nitrogen",
        symbol: "N",
        roomTempState: ENUM.State.Gas,
        series: ENUM.Series.ReactiveNonmetals,
        metal: ENUM.Metal.Nonmetal,
        group: ENUM.Group.Pnictogens,
        families: [],
        atomicMass: 14.007,
        electronegativity: 3.04,
        calculatedRadius: 56,
        electronAffinity: 7.0,
        firstIonization: 1402.3,
        period: 2,
        groupNum: 15,
        block: ENUM.Block.P,
    },
    {
        atomicNumber: 8,
        name: "Oxygen",
        symbol: "O",
        roomTempState: ENUM.State.Gas,
        series: ENUM.Series.ReactiveNonmetals,
        metal: ENUM.Metal.Nonmetal,
        group: ENUM.Group.Chalcogens,
        families: [],
        atomicMass: 15.999,
        electronegativity: 3.44,
        calculatedRadius: 48,
        electronAffinity: 141.0,
        firstIonization: 1313.9,
        period: 2,
        groupNum: 16,
        block: ENUM.Block.P,
    },
    {
        atomicNumber: 9,
        name: "Fluorine",
        symbol: "F",
        roomTempState: ENUM.State.Gas,
        series: ENUM.Series.ReactiveNonmetals,
        metal: ENUM.Metal.Nonmetal,
        group: ENUM.Group.Halogens,
        families: [],
        atomicMass: 18.998,
        electronegativity: 3.98,
        calculatedRadius: 42,
        electronAffinity: 328.0,
        firstIonization: 1681.0,
        period: 2,
        groupNum: 17,
        block: ENUM.Block.P,
    },
    {
        atomicNumber: 10,
        name: "Neon",
        symbol: "Ne",
        roomTempState: ENUM.State.Gas,
        series: ENUM.Series.NobleGases,
        metal: ENUM.Metal.Nonmetal,
        group: ENUM.Group.NobleGasses,
        families: [],
        atomicMass: 20.180,
        electronegativity: null,
        calculatedRadius: 38,
        electronAffinity: null,
        firstIonization: 2080.7,
        period: 2,
        groupNum: 18,
        block: ENUM.Block.P,
    },
    {
        atomicNumber: 11,
        name: "Sodium",
        symbol: "Na",
        roomTempState: ENUM.State.Solid,
        series: ENUM.Series.AlkaliMetals,
        metal: ENUM.Metal.Metal,
        group: ENUM.Group.AlkaliMetals,
        families: [],
        atomicMass: 22.990,
        electronegativity: 0.93,
        calculatedRadius: 190,
        electronAffinity: 52.8,
        firstIonization: 495.8,
        period: 3,
        groupNum: 1,
        block: ENUM.Block.S,
    },
    {
        atomicNumber: 12,
        name: "Magnesium",
        symbol: "Mg",
        roomTempState: ENUM.State.Solid,
        series: ENUM.Series.AlkalineEarthMetals,
        metal: ENUM.Metal.Metal,
        group: ENUM.Group.AlkalineEarthMetals,
        families: [],
        atomicMass: 24.305,
        electronegativity: 1.31,
        calculatedRadius: 145,
        electronAffinity: null,
        firstIonization: 737.7,
        period: 3,
        groupNum: 2,
        block: ENUM.Block.S,
    },
    {
        atomicNumber: 13,
        name: "Aluminum",
        symbol: "Al",
        roomTempState: ENUM.State.Solid,
        series: ENUM.Series.PostTransitionMetals,
        metal: ENUM.Metal.Metal,
        group: ENUM.Group.Triels,
        families: [],
        atomicMass: 26.982,
        electronegativity: 1.61,
        calculatedRadius: 118,
        electronAffinity: 42.5,
        firstIonization: 577.5,
        period: 3,
        groupNum: 13,
        block: ENUM.Block.P,
    },
    {
        atomicNumber: 14,
        name: "Silicon",
        symbol: "Si",
        roomTempState: ENUM.State.Solid,
        series: ENUM.Series.Metalloids,
        metal: ENUM.Metal.Metalloid,
        group: ENUM.Group.Tetrels,
        families: [],
        atomicMass: 28.086,
        electronegativity: 1.90,
        calculatedRadius: 111,
        electronAffinity: 133.6,
        firstIonization: 786.5,
        period: 3,
        groupNum: 14,
        block: ENUM.Block.P,
    },
    {
        atomicNumber: 15,
        name: "Phosphorus",
        symbol: "P",
        roomTempState: ENUM.State.Solid,
        series: ENUM.Series.ReactiveNonmetals,
        metal: ENUM.Metal.Nonmetal,
        group: ENUM.Group.Pnictogens,
        families: [],
        atomicMass: 30.974,
        electronegativity: 2.19,
        calculatedRadius: 98,
        electronAffinity: 72.0,
        firstIonization: 1011.8,
        period: 3,
        groupNum: 15,
        block: ENUM.Block.P,
    },
    {
        atomicNumber: 16,
        name: "Sulfur",
        symbol: "S",
        roomTempState: ENUM.State.Solid,
        series: ENUM.Series.ReactiveNonmetals,
        metal: ENUM.Metal.Nonmetal,
        group: ENUM.Group.Chalcogens,
        families: [],
        atomicMass: 32.065,
        electronegativity: 2.58,
        calculatedRadius: 88,
        electronAffinity: 200.0,
        firstIonization: 999.6,
        period: 3,
        groupNum: 16,
        block: ENUM.Block.P,
    },
    {
        atomicNumber: 17,
        name: "Chlorine",
        symbol: "Cl",
        roomTempState: ENUM.State.Gas,
        series: ENUM.Series.ReactiveNonmetals,
        metal: ENUM.Metal.Nonmetal,
        group: ENUM.Group.Halogens,
        families: [],
        atomicMass: 35.453,
        electronegativity: 3.16,
        calculatedRadius: 79,
        electronAffinity: 349.0,
        firstIonization: 1251.2,
        period: 3,
        groupNum: 17,
        block: ENUM.Block.P,
    },
    {
        atomicNumber: 18,
        name: "Argon",
        symbol: "Ar",
        roomTempState: ENUM.State.Gas,
        series: ENUM.Series.NobleGases,
        metal: ENUM.Metal.Nonmetal,
        group: ENUM.Group.NobleGasses,
        families: [],
        atomicMass: 39.948,
        electronegativity: null,
        calculatedRadius: 71,
        electronAffinity: null,
        firstIonization: 1520.6,
        period: 3,
        groupNum: 18,
        block: ENUM.Block.P,
    },
    {
        atomicNumber: 19,
        name: "Potassium",
        symbol: "K",
        roomTempState: ENUM.State.Solid,
        series: ENUM.Series.AlkaliMetals,
        metal: ENUM.Metal.Metal,
        group: ENUM.Group.AlkaliMetals,
        families: [],
        atomicMass: 39.098,
        electronegativity: 0.82,
        calculatedRadius: 243,
        electronAffinity: 48.4,
        firstIonization: 418.8,
        period: 4,
        groupNum: 1,
        block: ENUM.Block.S,
    },
    {
        atomicNumber: 20,
        name: "Calcium",
        symbol: "Ca",
        roomTempState: ENUM.State.Solid,
        series: ENUM.Series.AlkalineEarthMetals,
        metal: ENUM.Metal.Metal,
        group: ENUM.Group.AlkalineEarthMetals,
        families: [],
        atomicMass: 40.078,
        electronegativity: 1.00,
        calculatedRadius: 194,
        electronAffinity: 2.37,
        firstIonization: 589.8,
        period: 4,
        groupNum: 2,
        block: ENUM.Block.S,
    },
    {
        atomicNumber: 21,
        name: "Scandium",
        symbol: "Sc",
        roomTempState: ENUM.State.Solid,
        series: ENUM.Series.TransitionMetals,
        metal: ENUM.Metal.Metal,
        group: ENUM.Group.Transition,
        families: [],
        atomicMass: 44.956,
        electronegativity: 1.36,
        calculatedRadius: 184,
        electronAffinity: 18.1,
        firstIonization: 633.1,
        period: 4,
        groupNum: 3,
        block: ENUM.Block.D,
    },
    {
        atomicNumber: 22,
        name: "Titanium",
        symbol: "Ti",
        roomTempState: ENUM.State.Solid,
        series: ENUM.Series.TransitionMetals,
        metal: ENUM.Metal.Metal,
        group: ENUM.Group.Transition,
        families: [],
        atomicMass: 47.867,
        electronegativity: 1.54,
        calculatedRadius: 176,
        electronAffinity: 7.6,
        firstIonization: 658.8,
        period: 4,
        groupNum: 4,
        block: ENUM.Block.D,
    },
    {
        atomicNumber: 23,
        name: "Vanadium",
        symbol: "V",
        roomTempState: ENUM.State.Solid,
        series: ENUM.Series.TransitionMetals,
        metal: ENUM.Metal.Metal,
        group: ENUM.Group.Transition,
        families: [],
        atomicMass: 50.942,
        electronegativity: 1.63,
        calculatedRadius: 171,
        electronAffinity: 50.6,
        firstIonization: 650.9,
        period: 4,
        groupNum: 5,
        block: ENUM.Block.D,
    },
    {
        atomicNumber: 24,
        name: "Chromium",
        symbol: "Cr",
        roomTempState: ENUM.State.Solid,
        series: ENUM.Series.TransitionMetals,
        metal: ENUM.Metal.Metal,
        group: ENUM.Group.Transition,
        families: [],
        atomicMass: 51.996,
        electronegativity: 1.66,
        calculatedRadius: 166,
        electronAffinity: 64.3,
        firstIonization: 652.9,
        period: 4,
        groupNum: 6,
        block: ENUM.Block.D,
    },
    {
        atomicNumber: 25,
        name: "Manganese",
        symbol: "Mn",
        roomTempState: ENUM.State.Solid,
        series: ENUM.Series.TransitionMetals,
        metal: ENUM.Metal.Metal,
        group: ENUM.Group.Transition,
        families: [],
        atomicMass: 54.938,
        electronegativity: 1.55,
        calculatedRadius: 161,
        electronAffinity: null,
        firstIonization: 717.3,
        period: 4,
        groupNum: 7,
        block: ENUM.Block.D,
    },
    {
        atomicNumber: 26,
        name: "Iron",
        symbol: "Fe",
        roomTempState: ENUM.State.Solid,
        series: ENUM.Series.TransitionMetals,
        metal: ENUM.Metal.Metal,
        group: ENUM.Group.Transition,
        families: [],
        atomicMass: 55.845,
        electronegativity: 1.83,
        calculatedRadius: 156,
        electronAffinity: 15.7,
        firstIonization: 762.5,
        period: 4,
        groupNum: 8,
        block: ENUM.Block.D,
    },
    {
        atomicNumber: 27,
        name: "Cobalt",
        symbol: "Co",
        roomTempState: ENUM.State.Solid,
        series: ENUM.Series.TransitionMetals,
        metal: ENUM.Metal.Metal,
        group: ENUM.Group.Transition,
        families: [],
        atomicMass: 58.933,
        electronegativity: 1.88,
        calculatedRadius: 152,
        electronAffinity: 63.7,
        firstIonization: 760.4,
        period: 4,
        groupNum: 9,
        block: ENUM.Block.D,
    },
    {
        atomicNumber: 28,
        name: "Nickel",
        symbol: "Ni",
        roomTempState: ENUM.State.Solid,
        series: ENUM.Series.TransitionMetals,
        metal: ENUM.Metal.Metal,
        group: ENUM.Group.Transition,
        families: [],
        atomicMass: 58.693,
        electronegativity: 1.91,
        calculatedRadius: 149,
        electronAffinity: 112.0,
        firstIonization: 737.1,
        period: 4,
        groupNum: 10,
        block: ENUM.Block.D,
    },
    {
        atomicNumber: 29,
        name: "Copper",
        symbol: "Cu",
        roomTempState: ENUM.State.Solid,
        series: ENUM.Series.TransitionMetals,
        metal: ENUM.Metal.Metal,
        group: ENUM.Group.Transition,
        families: [],
        atomicMass: 63.546,
        electronegativity: 1.90,
        calculatedRadius: 145,
        electronAffinity: 118.4,
        firstIonization: 745.5,
        period: 4,
        groupNum: 11,
        block: ENUM.Block.D,
    },
    {
        atomicNumber: 30,
        name: "Zinc",
        symbol: "Zn",
        roomTempState: ENUM.State.Solid,
        series: ENUM.Series.TransitionMetals,
        metal: ENUM.Metal.Metal,
        group: ENUM.Group.Transition,
        families: [],
        atomicMass: 65.38,
        electronegativity: 1.65,
        calculatedRadius: 142,
        electronAffinity: null,
        firstIonization: 906.4,
        period: 4,
        groupNum: 12,
        block: ENUM.Block.D,
    },
    {
        atomicNumber: 31,
        name: "Gallium",
        symbol: "Ga",
        roomTempState: ENUM.State.Solid,
        series: ENUM.Series.PostTransitionMetals,
        metal: ENUM.Metal.Metal,
        group: ENUM.Group.Triels,
        families: [],
        atomicMass: 69.723,
        electronegativity: 1.81,
        calculatedRadius: 136,
        electronAffinity: 28.9,
        firstIonization: 578.8,
        period: 4,
        groupNum: 13,
        block: ENUM.Block.P,
    },
    {
        atomicNumber: 32,
        name: "Germanium",
        symbol: "Ge",
        roomTempState: ENUM.State.Solid,
        series: ENUM.Series.Metalloids,
        metal: ENUM.Metal.Metalloid,
        group: ENUM.Group.Tetrels,
        families: [],
        atomicMass: 72.64,
        electronegativity: 2.01,
        calculatedRadius: 125,
        electronAffinity: 119.0,
        firstIonization: 762.0,
        period: 4,
        groupNum: 14,
        block: ENUM.Block.P,
    },
    {
        atomicNumber: 33,
        name: "Arsenic",
        symbol: "As",
        roomTempState: ENUM.State.Solid,
        series: ENUM.Series.Metalloids,
        metal: ENUM.Metal.Metalloid,
        group: ENUM.Group.Pnictogens,
        families: [],
        atomicMass: 74.922,
        electronegativity: 2.18,
        calculatedRadius: 114,
        electronAffinity: 78.0,
        firstIonization: 947.0,
        period: 4,
        groupNum: 15,
        block: ENUM.Block.P,
    },
    {
        atomicNumber: 34,
        name: "Selenium",
        symbol: "Se",
        roomTempState: ENUM.State.Solid,
        series: ENUM.Series.ReactiveNonmetals,
        metal: ENUM.Metal.Nonmetal,
        group: ENUM.Group.Chalcogens,
        families: [],
        atomicMass: 78.96,
        electronegativity: 2.55,
        calculatedRadius: 103,
        electronAffinity: 195.0,
        firstIonization: 941.0,
        period: 4,
        groupNum: 16,
        block: ENUM.Block.P,
    },
    {
        atomicNumber: 35,
        name: "Bromine",
        symbol: "Br",
        roomTempState: ENUM.State.Liquid,
        series: ENUM.Series.ReactiveNonmetals,
        metal: ENUM.Metal.Nonmetal,
        group: ENUM.Group.Halogens,
        families: [],
        atomicMass: 79.904,
        electronegativity: 2.96,
        calculatedRadius: 94,
        electronAffinity: 324.6,
        firstIonization: 1139.9,
        period: 4,
        groupNum: 17,
        block: ENUM.Block.P,
    },
    {
        atomicNumber: 36,
        name: "Krypton",
        symbol: "Kr",
        roomTempState: ENUM.State.Gas,
        series: ENUM.Series.NobleGases,
        metal: ENUM.Metal.Nonmetal,
        group: ENUM.Group.NobleGasses,
        families: [],
        atomicMass: 83.798,
        electronegativity: 3.00,
        calculatedRadius: 88,
        electronAffinity: null,
        firstIonization: 1350.8,
        period: 4,
        groupNum: 18,
        block: ENUM.Block.P,
    },
    {
        atomicNumber: 37,
        name: "Rubidium",
        symbol: "Rb",
        roomTempState: ENUM.State.Solid,
        series: ENUM.Series.AlkaliMetals,
        metal: ENUM.Metal.Metal,
        group: ENUM.Group.AlkaliMetals,
        families: [],
        atomicMass: 85.468,
        electronegativity: 0.82,
        calculatedRadius: 265,
        electronAffinity: 46.9,
        firstIonization: 403.0,
        period: 5,
        groupNum: 1,
        block: ENUM.Block.S,
    },
    {
        atomicNumber: 38,
        name: "Strontium",
        symbol: "Sr",
        roomTempState: ENUM.State.Solid,
        series: ENUM.Series.AlkalineEarthMetals,
        metal: ENUM.Metal.Metal,
        group: ENUM.Group.AlkalineEarthMetals,
        families: [],
        atomicMass: 87.62,
        electronegativity: 0.95,
        calculatedRadius: 219,
        electronAffinity: 5.03,
        firstIonization: 549.5,
        period: 5,
        groupNum: 2,
        block: ENUM.Block.S,
    },
    {
        atomicNumber: 39,
        name: "Yttrium",
        symbol: "Y",
        roomTempState: ENUM.State.Solid,
        series: ENUM.Series.TransitionMetals,
        metal: ENUM.Metal.Metal,
        group: ENUM.Group.Transition,
        families: [],
        atomicMass: 88.906,
        electronegativity: 1.22,
        calculatedRadius: 212,
        electronAffinity: 29.6,
        firstIonization: 600.0,
        period: 5,
        groupNum: 3,
        block: ENUM.Block.D,
    },
    {
        atomicNumber: 40,
        name: "Zirconium",
        symbol: "Zr",
        roomTempState: ENUM.State.Solid,
        series: ENUM.Series.TransitionMetals,
        metal: ENUM.Metal.Metal,
        group: ENUM.Group.Transition,
        families: [],
        atomicMass: 91.224,
        electronegativity: 1.33,
        calculatedRadius: 206,
        electronAffinity: 41.1,
        firstIonization: 640.1,
        period: 5,
        groupNum: 4,
        block: ENUM.Block.D,
    },
    {
        atomicNumber: 41,
        name: "Niobium",
        symbol: "Nb",
        roomTempState: ENUM.State.Solid,
        series: ENUM.Series.TransitionMetals,
        metal: ENUM.Metal.Metal,
        group: ENUM.Group.Transition,
        families: [],
        atomicMass: 92.906,
        electronegativity: 1.6,
        calculatedRadius: 198,
        electronAffinity: 86.1,
        firstIonization: 652.1,
        period: 5,
        groupNum: 5,
        block: ENUM.Block.D,
    },
    {
        atomicNumber: 42,
        name: "Molybdenum",
        symbol: "Mo",
        roomTempState: ENUM.State.Solid,
        series: ENUM.Series.TransitionMetals,
        metal: ENUM.Metal.Metal,
        group: ENUM.Group.Transition,
        families: [],
        atomicMass: 95.96,
        electronegativity: 2.16,
        calculatedRadius: 190,
        electronAffinity: 71.9,
        firstIonization: 684.3,
        period: 5,
        groupNum: 6,
        block: ENUM.Block.D,
    },
    {
        atomicNumber: 43,
        name: "Technetium",
        symbol: "Tc",
        roomTempState: ENUM.State.Solid,
        series: ENUM.Series.TransitionMetals,
        metal: ENUM.Metal.Metal,
        group: ENUM.Group.Transition,
        families: [ENUM.Family.Radioactive],
        atomicMass: 98,
        electronegativity: 1.9,
        calculatedRadius: 183,
        electronAffinity: 53.0,
        firstIonization: 702.0,
        period: 5,
        groupNum: 7,
        block: ENUM.Block.D,
    },
    {
        atomicNumber: 44,
        name: "Ruthenium",
        symbol: "Ru",
        roomTempState: ENUM.State.Solid,
        series: ENUM.Series.TransitionMetals,
        metal: ENUM.Metal.Metal,
        group: ENUM.Group.Transition,
        families: [],
        atomicMass: 101.07,
        electronegativity: 2.2,
        calculatedRadius: 178,
        electronAffinity: 101.3,
        firstIonization: 710.2,
        period: 5,
        groupNum: 8,
        block: ENUM.Block.D,
    },
    {
        atomicNumber: 45,
        name: "Rhodium",
        symbol: "Rh",
        roomTempState: ENUM.State.Solid,
        series: ENUM.Series.TransitionMetals,
        metal: ENUM.Metal.Metal,
        group: ENUM.Group.Transition,
        families: [],
        atomicMass: 102.91,
        electronegativity: 2.28,
        calculatedRadius: 173,
        electronAffinity: 110.0,
        firstIonization: 719.7,
        period: 5,
        groupNum: 9,
        block: ENUM.Block.D,
    },
    {
        atomicNumber: 46,
        name: "Palladium",
        symbol: "Pd",
        roomTempState: ENUM.State.Solid,
        series: ENUM.Series.TransitionMetals,
        metal: ENUM.Metal.Metal,
        group: ENUM.Group.Transition,
        families: [],
        atomicMass: 106.42,
        electronegativity: 2.20,
        calculatedRadius: 169,
        electronAffinity: 54.24,
        firstIonization: 804.4,
        period: 5,
        groupNum: 10,
        block: ENUM.Block.D,
    },
    {
        atomicNumber: 47,
        name: "Silver",
        symbol: "Ag",
        roomTempState: ENUM.State.Solid,
        series: ENUM.Series.TransitionMetals,
        metal: ENUM.Metal.Metal,
        group: ENUM.Group.Transition,
        families: [],
        atomicMass: 107.87,
        electronegativity: 1.93,
        calculatedRadius: 165,
        electronAffinity: 125.6,
        firstIonization: 731.0,
        period: 5,
        groupNum: 11,
        block: ENUM.Block.D,
    },
    {
        atomicNumber: 48,
        name: "Cadmium",
        symbol: "Cd",
        roomTempState: ENUM.State.Solid,
        series: ENUM.Series.TransitionMetals,
        metal: ENUM.Metal.Metal,
        group: ENUM.Group.Transition,
        families: [],
        atomicMass: 112.41,
        electronegativity: 1.69,
        calculatedRadius: 161,
        electronAffinity: null,
        firstIonization: 867.8,
        period: 5,
        groupNum: 12,
        block: ENUM.Block.D,
    },
    {
        atomicNumber: 49,
        name: "Indium",
        symbol: "In",
        roomTempState: ENUM.State.Solid,
        series: ENUM.Series.PostTransitionMetals,
        metal: ENUM.Metal.Metal,
        group: ENUM.Group.Triels,
        families: [],
        atomicMass: 114.82,
        electronegativity: 1.78,
        calculatedRadius: 156,
        electronAffinity: 28.9,
        firstIonization: 558.3,
        period: 5,
        groupNum: 13,
        block: ENUM.Block.P,
    },
    {
        atomicNumber: 50,
        name: "Tin",
        symbol: "Sn",
        roomTempState: ENUM.State.Solid,
        series: ENUM.Series.PostTransitionMetals,
        metal: ENUM.Metal.Metal,
        group: ENUM.Group.Tetrels,
        families: [],
        atomicMass: 118.71,
        electronegativity: 1.96,
        calculatedRadius: 145,
        electronAffinity: 107.3,
        firstIonization: 708.6,
        period: 5,
        groupNum: 14,
        block: ENUM.Block.P,
    },
    {
        atomicNumber: 51,
        name: "Antimony",
        symbol: "Sb",
        roomTempState: ENUM.State.Solid,
        series: ENUM.Series.Metalloids,
        metal: ENUM.Metal.Metalloid,
        group: ENUM.Group.Pnictogens,
        families: [],
        atomicMass: 121.76,
        electronegativity: 2.05,
        calculatedRadius: 133,
        electronAffinity: 103.2,
        firstIonization: 834.0,
        period: 5,
        groupNum: 15,
        block: ENUM.Block.P,
    },
    {
        atomicNumber: 52,
        name: "Tellurium",
        symbol: "Te",
        roomTempState: ENUM.State.Solid,
        series: ENUM.Series.Metalloids,
        metal: ENUM.Metal.Metalloid,
        group: ENUM.Group.Chalcogens,
        families: [],
        atomicMass: 127.60,
        electronegativity: 2.1,
        calculatedRadius: 123,
        electronAffinity: 190.2,
        firstIonization: 869.3,
        period: 5,
        groupNum: 16,
        block: ENUM.Block.P,
    },
    {
        atomicNumber: 53,
        name: "Iodine",
        symbol: "I",
        roomTempState: ENUM.State.Solid,
        series: ENUM.Series.ReactiveNonmetals,
        metal: ENUM.Metal.Nonmetal,
        group: ENUM.Group.Halogens,
        families: [],
        atomicMass: 126.90,
        electronegativity: 2.66,
        calculatedRadius: 115,
        electronAffinity: 295.2,
        firstIonization: 1008.4,
        period: 5,
        groupNum: 17,
        block: ENUM.Block.P,
    },
    {
        atomicNumber: 54,
        name: "Xenon",
        symbol: "Xe",
        roomTempState: ENUM.State.Gas,
        series: ENUM.Series.NobleGases,
        metal: ENUM.Metal.Nonmetal,
        group: ENUM.Group.NobleGasses,
        families: [],
        atomicMass: 131.29,
        electronegativity: 2.60,
        calculatedRadius: 108,
        electronAffinity: null,
        firstIonization: 1170.4,
        period: 5,
        groupNum: 18,
        block: ENUM.Block.P,
    },
    {
        atomicNumber: 55,
        name: "Cesium",
        symbol: "Cs",
        roomTempState: ENUM.State.Solid,
        series: ENUM.Series.AlkaliMetals,
        metal: ENUM.Metal.Metal,
        group: ENUM.Group.AlkaliMetals,
        families: [],
        atomicMass: 132.91,
        electronegativity: 0.79,
        calculatedRadius: 298,
        electronAffinity: 45.5,
        firstIonization: 375.7,
        period: 6,
        groupNum: 1,
        block: ENUM.Block.S,
    },
    {
        atomicNumber: 56,
        name: "Barium",
        symbol: "Ba",
        roomTempState: ENUM.State.Solid,
        series: ENUM.Series.AlkalineEarthMetals,
        metal: ENUM.Metal.Metal,
        group: ENUM.Group.AlkalineEarthMetals,
        families: [],
        atomicMass: 137.33,
        electronegativity: 0.89,
        calculatedRadius: 253,
        electronAffinity: 13.95,
        firstIonization: 502.9,
        period: 6,
        groupNum: 2,
        block: ENUM.Block.S,
    },
    {
        atomicNumber: 57,
        name: "Lanthanum",
        symbol: "La",
        roomTempState: ENUM.State.Solid,
        series: ENUM.Series.Lanthanoids,
        metal: ENUM.Metal.Metal,
        group: ENUM.Group.Lanthanoids,
        families: [],
        atomicMass: 138.91,
        electronegativity: 1.10,
        calculatedRadius: 226,
        electronAffinity: 48.0,
        firstIonization: 538.1,
        period: 6,
        groupNum: null,
        block: ENUM.Block.F,
    },
    {
        atomicNumber: 58,
        name: "Cerium",
        symbol: "Ce",
        roomTempState: ENUM.State.Solid,
        series: ENUM.Series.Lanthanoids,
        metal: ENUM.Metal.Metal,
        group: ENUM.Group.Lanthanoids,
        families: [],
        atomicMass: 140.12,
        electronegativity: 1.12,
        calculatedRadius: 210,
        electronAffinity: 50.0,
        firstIonization: 534.4,
        period: 6,
        groupNum: null,
        block: ENUM.Block.F,
    },
    {
        atomicNumber: 59,
        name: "Praseodymium",
        symbol: "Pr",
        roomTempState: ENUM.State.Solid,
        series: ENUM.Series.Lanthanoids,
        metal: ENUM.Metal.Metal,
        group: ENUM.Group.Lanthanoids,
        families: [],
        atomicMass: 140.91,
        electronegativity: 1.13,
        calculatedRadius: 247,
        electronAffinity: 50.0,
        firstIonization: 527.0,
        period: 6,
        groupNum: null,
        block: ENUM.Block.F,
    },
    {
        atomicNumber: 60,
        name: "Neodymium",
        symbol: "Nd",
        roomTempState: ENUM.State.Solid,
        series: ENUM.Series.Lanthanoids,
        metal: ENUM.Metal.Metal,
        group: ENUM.Group.Lanthanoids,
        families: [],
        atomicMass: 144.24,
        electronegativity: 1.14,
        calculatedRadius: 206,
        electronAffinity: 50.0,
        firstIonization: 533.1,
        period: 6,
        groupNum: null,
        block: ENUM.Block.F,
    },
    {
        atomicNumber: 61,
        name: "Promethium",
        symbol: "Pm",
        roomTempState: ENUM.State.Solid,
        series: ENUM.Series.Lanthanoids,
        metal: ENUM.Metal.Metal,
        group: ENUM.Group.Lanthanoids,
        families: [],
        atomicMass: 145,
        electronegativity: 1.13,
        calculatedRadius: 205,
        electronAffinity: 50.0,
        firstIonization: 540.0,
        period: 6,
        groupNum: null,
        block: ENUM.Block.F,
    },
    {
        atomicNumber: 62,
        name: "Samarium",
        symbol: "Sm",
        roomTempState: ENUM.State.Solid,
        series: ENUM.Series.Lanthanoids,
        metal: ENUM.Metal.Metal,
        group: ENUM.Group.Lanthanoids,
        families: [],
        atomicMass: 150.36,
        electronegativity: 1.17,
        calculatedRadius: 238,
        electronAffinity: 50.0,
        firstIonization: 544.5,
        period: 6,
        groupNum: null,
        block: ENUM.Block.F,
    },
    {
        atomicNumber: 63,
        name: "Europium",
        symbol: "Eu",
        roomTempState: ENUM.State.Solid,
        series: ENUM.Series.Lanthanoids,
        metal: ENUM.Metal.Metal,
        group: ENUM.Group.Lanthanoids,
        families: [],
        atomicMass: 151.96,
        electronegativity: 1.2,
        calculatedRadius: 231,
        electronAffinity: 50.0,
        firstIonization: 547.1,
        period: 6,
        groupNum: null,
        block: ENUM.Block.F,
    },
    {
        atomicNumber: 64,
        name: "Gadolinium",
        symbol: "Gd",
        roomTempState: ENUM.State.Solid,
        series: ENUM.Series.Lanthanoids,
        metal: ENUM.Metal.Metal,
        group: ENUM.Group.Lanthanoids,
        families: [],
        atomicMass: 157.25,
        electronegativity: 1.20,
        calculatedRadius: 233,
        electronAffinity: 50.0,
        firstIonization: 593.4,
        period: 6,
        groupNum: null,
        block: ENUM.Block.F,
    },
    {
        atomicNumber: 65,
        name: "Terbium",
        symbol: "Tb",
        roomTempState: ENUM.State.Solid,
        series: ENUM.Series.Lanthanoids,
        metal: ENUM.Metal.Metal,
        group: ENUM.Group.Lanthanoids,
        families: [],
        atomicMass: 158.93,
        electronegativity: 1.2,
        calculatedRadius: 225,
        electronAffinity: 50.0,
        firstIonization: 565.8,
        period: 6,
        groupNum: null,
        block: ENUM.Block.F,
    },
    {
        atomicNumber: 66,
        name: "Dysprosium",
        symbol: "Dy",
        roomTempState: ENUM.State.Solid,
        series: ENUM.Series.Lanthanoids,
        metal: ENUM.Metal.Metal,
        group: ENUM.Group.Lanthanoids,
        families: [],
        atomicMass: 162.50,
        electronegativity: 1.22,
        calculatedRadius: 228,
        electronAffinity: 50.0,
        firstIonization: 573.0,
        period: 6,
        groupNum: null,
        block: ENUM.Block.F,
    },
    {
        atomicNumber: 67,
        name: "Holmium",
        symbol: "Ho",
        roomTempState: ENUM.State.Solid,
        series: ENUM.Series.Lanthanoids,
        metal: ENUM.Metal.Metal,
        group: ENUM.Group.Lanthanoids,
        families: [],
        atomicMass: 164.93,
        electronegativity: 1.23,
        calculatedRadius: 226,
        electronAffinity: 50.0,
        firstIonization: 581.0,
        period: 6,
        groupNum: null,
        block: ENUM.Block.F,
    },
    {
        atomicNumber: 68,
        name: "Erbium",
        symbol: "Er",
        roomTempState: ENUM.State.Solid,
        series: ENUM.Series.Lanthanoids,
        metal: ENUM.Metal.Metal,
        group: ENUM.Group.Lanthanoids,
        families: [],
        atomicMass: 167.26,
        electronegativity: 1.24,
        calculatedRadius: 226,
        electronAffinity: 50.0,
        firstIonization: 589.3,
        period: 6,
        groupNum: null,
        block: ENUM.Block.F,
    },
    {
        atomicNumber: 69,
        name: "Thulium",
        symbol: "Tm",
        roomTempState: ENUM.State.Solid,
        series: ENUM.Series.Lanthanoids,
        metal: ENUM.Metal.Metal,
        group: ENUM.Group.Lanthanoids,
        families: [],
        atomicMass: 168.93,
        electronegativity: 1.25,
        calculatedRadius: 222,
        electronAffinity: 50.0,
        firstIonization: 596.7,
        period: 6,
        groupNum: null,
        block: ENUM.Block.F,
    },
    {
        atomicNumber: 70,
        name: "Ytterbium",
        symbol: "Yb",
        roomTempState: ENUM.State.Solid,
        series: ENUM.Series.Lanthanoids,
        metal: ENUM.Metal.Metal,
        group: ENUM.Group.Lanthanoids,
        families: [],
        atomicMass: 173.05,
        electronegativity: 1.1,
        calculatedRadius: 222,
        electronAffinity: 50.0,
        firstIonization: 603.4,
        period: 6,
        groupNum: null,
        block: ENUM.Block.F,
    },
    {
        atomicNumber: 71,
        name: "Lutetium",
        symbol: "Lu",
        roomTempState: ENUM.State.Solid,
        series: ENUM.Series.Lanthanoids,
        metal: ENUM.Metal.Metal,
        group: ENUM.Group.Lanthanoids,
        families: [],
        atomicMass: 174.97,
        electronegativity: 1.27,
        calculatedRadius: 217,
        electronAffinity: 50.0,
        firstIonization: 523.5,
        period: 6,
        groupNum: null,
        block: ENUM.Block.F,
    },
    {
        atomicNumber: 72,
        name: "Hafnium",
        symbol: "Hf",
        roomTempState: ENUM.State.Solid,
        series: ENUM.Series.TransitionMetals,
        metal: ENUM.Metal.Metal,
        group: ENUM.Group.Transition,
        families: [],
        atomicMass: 178.49,
        electronegativity: 1.3,
        calculatedRadius: 208,
        electronAffinity: 0.0,
        firstIonization: 658.5,
        period: 6,
        groupNum: 4,
        block: ENUM.Block.D,
    },
    {
        atomicNumber: 73,
        name: "Tantalum",
        symbol: "Ta",
        roomTempState: ENUM.State.Solid,
        series: ENUM.Series.TransitionMetals,
        metal: ENUM.Metal.Metal,
        group: ENUM.Group.Transition,
        families: [],
        atomicMass: 180.95,
        electronegativity: 1.5,
        calculatedRadius: 200,
        electronAffinity: 31.0,
        firstIonization: 761.0,
        period: 6,
        groupNum: 5,
        block: ENUM.Block.D,
    },
    {
        atomicNumber: 74,
        name: "Tungsten",
        symbol: "W",
        roomTempState: ENUM.State.Solid,
        series: ENUM.Series.TransitionMetals,
        metal: ENUM.Metal.Metal,
        group: ENUM.Group.Transition,
        families: [],
        atomicMass: 183.84,
        electronegativity: 2.36,
        calculatedRadius: 193,
        electronAffinity: 78.6,
        firstIonization: 770.0,
        period: 6,
        groupNum: 6,
        block: ENUM.Block.D,
    },
    {
        atomicNumber: 75,
        name: "Rhenium",
        symbol: "Re",
        roomTempState: ENUM.State.Solid,
        series: ENUM.Series.TransitionMetals,
        metal: ENUM.Metal.Metal,
        group: ENUM.Group.Transition,
        families: [],
        atomicMass: 186.21,
        electronegativity: 1.9,
        calculatedRadius: 188,
        electronAffinity: 14.5,
        firstIonization: 760.0,
        period: 6,
        groupNum: 7,
        block: ENUM.Block.D,
    },
    {
        atomicNumber: 76,
        name: "Osmium",
        symbol: "Os",
        roomTempState: ENUM.State.Solid,
        series: ENUM.Series.TransitionMetals,
        metal: ENUM.Metal.Metal,
        group: ENUM.Group.Transition,
        families: [],
        atomicMass: 190.23,
        electronegativity: 2.2,
        calculatedRadius: 185,
        electronAffinity: 106.1,
        firstIonization: 840.0,
        period: 6,
        groupNum: 8,
        block: ENUM.Block.D,
    },
    {
        atomicNumber: 77,
        name: "Iridium",
        symbol: "Ir",
        roomTempState: ENUM.State.Solid,
        series: ENUM.Series.TransitionMetals,
        metal: ENUM.Metal.Metal,
        group: ENUM.Group.Transition,
        families: [],
        atomicMass: 192.22,
        electronegativity: 2.20,
        calculatedRadius: 180,
        electronAffinity: 151.0,
        firstIonization: 880.0,
        period: 6,
        groupNum: 9,
        block: ENUM.Block.D,
    },
    {
        atomicNumber: 78,
        name: "Platinum",
        symbol: "Pt",
        roomTempState: ENUM.State.Solid,
        series: ENUM.Series.TransitionMetals,
        metal: ENUM.Metal.Metal,
        group: ENUM.Group.Transition,
        families: [],
        atomicMass: 195.08,
        electronegativity: 2.28,
        calculatedRadius: 177,
        electronAffinity: 205.3,
        firstIonization: 870.0,
        period: 6,
        groupNum: 10,
        block: ENUM.Block.D,
    },
    {
        atomicNumber: 79,
        name: "Gold",
        symbol: "Au",
        roomTempState: ENUM.State.Solid,
        series: ENUM.Series.TransitionMetals,
        metal: ENUM.Metal.Metal,
        group: ENUM.Group.Transition,
        families: [],
        atomicMass: 196.97,
        electronegativity: 2.54,
        calculatedRadius: 174,
        electronAffinity: 222.8,
        firstIonization: 890.1,
        period: 6,
        groupNum: 11,
        block: ENUM.Block.D,
    },
    {
        atomicNumber: 80,
        name: "Mercury",
        symbol: "Hg",
        roomTempState: ENUM.State.Liquid,
        series: ENUM.Series.TransitionMetals,
        metal: ENUM.Metal.Metal,
        group: ENUM.Group.Transition,
        families: [],
        atomicMass: 200.59,
        electronegativity: 2.00,
        calculatedRadius: 171,
        electronAffinity: null,
        firstIonization: 1007.1,
        period: 6,
        groupNum: 12,
        block: ENUM.Block.D,
    },
    {
        atomicNumber: 81,
        name: "Thallium",
        symbol: "Tl",
        roomTempState: ENUM.State.Solid,
        series: ENUM.Series.PostTransitionMetals,
        metal: ENUM.Metal.Metal,
        group: ENUM.Group.Triels,
        families: [],
        atomicMass: 204.38,
        electronegativity: 1.62,
        calculatedRadius: 156,
        electronAffinity: 19.2,
        firstIonization: 589.4,
        period: 6,
        groupNum: 13,
        block: ENUM.Block.P,
    },
    {
        atomicNumber: 82,
        name: "Lead",
        symbol: "Pb",
        roomTempState: ENUM.State.Solid,
        series: ENUM.Series.PostTransitionMetals,
        metal: ENUM.Metal.Metal,
        group: ENUM.Group.Tetrels,
        families: [],
        atomicMass: 207.2,
        electronegativity: 2.33,
        calculatedRadius: 154,
        electronAffinity: 35.1,
        firstIonization: 715.6,
        period: 6,
        groupNum: 14,
        block: ENUM.Block.P,
    },
    {
        atomicNumber: 83,
        name: "Bismuth",
        symbol: "Bi",
        roomTempState: ENUM.State.Solid,
        series: ENUM.Series.PostTransitionMetals,
        metal: ENUM.Metal.Metal,
        group: ENUM.Group.Pnictogens,
        families: [ENUM.Family.Radioactive],
        atomicMass: 208.98,
        electronegativity: 2.02,
        calculatedRadius: 143,
        electronAffinity: 91.2,
        firstIonization: 703.0,
        period: 6,
        groupNum: 15,
        block: ENUM.Block.P,
    },
    {
        atomicNumber: 84,
        name: "Polonium",
        symbol: "Po",
        roomTempState: ENUM.State.Solid,
        series: ENUM.Series.PostTransitionMetals,
        metal: ENUM.Metal.Metal,
        group: ENUM.Group.Chalcogens,
        families: [ENUM.Family.Radioactive],
        atomicMass: 209,
        electronegativity: 2.0,
        calculatedRadius: 135,
        electronAffinity: 183.3,
        firstIonization: 812.1,
        period: 6,
        groupNum: 16,
        block: ENUM.Block.P,
    },
    {
        atomicNumber: 85,
        name: "Astatine",
        symbol: "At",
        roomTempState: ENUM.State.Solid,
        series: ENUM.Series.Metalloids,
        metal: ENUM.Metal.Metalloid,
        group: ENUM.Group.Halogens,
        families: [],
        atomicMass: 210,
        electronegativity: 2.2,
        calculatedRadius: 127,
        electronAffinity: 270.1,
        firstIonization: 920.0,
        period: 6,
        groupNum: 17,
        block: ENUM.Block.P,
    },
    {
        atomicNumber: 86,
        name: "Radon",
        symbol: "Rn",
        roomTempState: ENUM.State.Gas,
        series: ENUM.Series.NobleGases,
        metal: ENUM.Metal.Nonmetal,
        group: ENUM.Group.NobleGasses,
        families: [],
        atomicMass: 222,
        electronegativity: 2.2,
        calculatedRadius: 120,
        electronAffinity: null,
        firstIonization: 1037.0,
        period: 6,
        groupNum: 18,
        block: ENUM.Block.P,
    },
    {
        atomicNumber: 87,
        name: "Francium",
        symbol: "Fr",
        roomTempState: ENUM.State.Solid,
        series: ENUM.Series.AlkaliMetals,
        metal: ENUM.Metal.Metal,
        group: ENUM.Group.AlkaliMetals,
        families: [],
        atomicMass: 223,
        electronegativity: 0.7,
        calculatedRadius: 348,
        electronAffinity: 46.89,
        firstIonization: 380.0,
        period: 7,
        groupNum: 1,
        block: ENUM.Block.S,
    },
    {
        atomicNumber: 88,
        name: "Radium",
        symbol: "Ra",
        roomTempState: ENUM.State.Solid,
        series: ENUM.Series.AlkalineEarthMetals,
        metal: ENUM.Metal.Metal,
        group: ENUM.Group.AlkalineEarthMetals,
        families: [],
        atomicMass: 226,
        electronegativity: 0.9,
        calculatedRadius: 283,
        electronAffinity: 9.6485,
        firstIonization: 509.3,
        period: 7,
        groupNum: 2,
        block: ENUM.Block.S,
    },
    {
        atomicNumber: 89,
        name: "Actinium",
        symbol: "Ac",
        roomTempState: ENUM.State.Solid,
        series: ENUM.Series.Actinoids,
        metal: ENUM.Metal.Metal,
        group: ENUM.Group.Actinoids,
        families: [],
        atomicMass: 227,
        electronegativity: 1.1,
        calculatedRadius: 260,
        electronAffinity: 33.77,
        firstIonization: 499.0,
        period: 7,
        groupNum: null,
        block: ENUM.Block.F,
    },
    {
        atomicNumber: 90,
        name: "Thorium",
        symbol: "Th",
        roomTempState: ENUM.State.Solid,
        series: ENUM.Series.Actinoids,
        metal: ENUM.Metal.Metal,
        group: ENUM.Group.Actinoids,
        families: [],
        atomicMass: 232.04,
        electronegativity: 1.3,
        calculatedRadius: 237,
        electronAffinity: null,
        firstIonization: 587.0,
        period: 7,
        groupNum: null,
        block: ENUM.Block.F,
    },
    {
        atomicNumber: 91,
        name: "Protactinium",
        symbol: "Pa",
        roomTempState: ENUM.State.Solid,
        series: ENUM.Series.Actinoids,
        metal: ENUM.Metal.Metal,
        group: ENUM.Group.Actinoids,
        families: [],
        atomicMass: 231.04,
        electronegativity: 1.5,
        calculatedRadius: 243,
        electronAffinity: null,
        firstIonization: 568.0,
        period: 7,
        groupNum: null,
        block: ENUM.Block.F,
    },
    {
        atomicNumber: 92,
        name: "Uranium",
        symbol: "U",
        roomTempState: ENUM.State.Solid,
        series: ENUM.Series.Actinoids,
        metal: ENUM.Metal.Metal,
        group: ENUM.Group.Actinoids,
        families: [],
        atomicMass: 238.03,
        electronegativity: 1.38,
        calculatedRadius: 240,
        electronAffinity: null,
        firstIonization: 597.6,
        period: 7,
        groupNum: null,
        block: ENUM.Block.F,
    },
    {
        atomicNumber: 93,
        name: "Neptunium",
        symbol: "Np",
        roomTempState: ENUM.State.Solid,
        series: ENUM.Series.Actinoids,
        metal: ENUM.Metal.Metal,
        group: ENUM.Group.Actinoids,
        families: [],
        atomicMass: 237,
        electronegativity: 1.36,
        calculatedRadius: 239,
        electronAffinity: null,
        firstIonization: 604.5,
        period: 7,
        groupNum: null,
        block: ENUM.Block.F,
    },
    {
        atomicNumber: 94,
        name: "Plutonium",
        symbol: "Pu",
        roomTempState: ENUM.State.Solid,
        series: ENUM.Series.Actinoids,
        metal: ENUM.Metal.Metal,
        group: ENUM.Group.Actinoids,
        families: [],
        atomicMass: 244,
        electronegativity: 1.28,
        calculatedRadius: 243,
        electronAffinity: null,
        firstIonization: 584.7,
        period: 7,
        groupNum: null,
        block: ENUM.Block.F,
    },
    {
        atomicNumber: 95,
        name: "Americium",
        symbol: "Am",
        roomTempState: ENUM.State.Solid,
        series: ENUM.Series.Actinoids,
        metal: ENUM.Metal.Metal,
        group: ENUM.Group.Actinoids,
        families: [],
        atomicMass: 243,
        electronegativity: 1.13,
        calculatedRadius: 244,
        electronAffinity: null,
        firstIonization: 578.0,
        period: 7,
        groupNum: null,
        block: ENUM.Block.F,
    },
    {
        atomicNumber: 96,
        name: "Curium",
        symbol: "Cm",
        roomTempState: ENUM.State.Solid,
        series: ENUM.Series.Actinoids,
        metal: ENUM.Metal.Metal,
        group: ENUM.Group.Actinoids,
        families: [],
        atomicMass: 247,
        electronegativity: 1.28,
        calculatedRadius: 245,
        electronAffinity: null,
        firstIonization: 581.0,
        period: 7,
        groupNum: null,
        block: ENUM.Block.F,
    },
    {
        atomicNumber: 97,
        name: "Berkelium",
        symbol: "Bk",
        roomTempState: ENUM.State.Solid,
        series: ENUM.Series.Actinoids,
        metal: ENUM.Metal.Metal,
        group: ENUM.Group.Actinoids,
        families: [],
        atomicMass: 247,
        electronegativity: 1.3,
        calculatedRadius: 244,
        electronAffinity: null,
        firstIonization: 601.0,
        period: 7,
        groupNum: null,
        block: ENUM.Block.F,
    },
    {
        atomicNumber: 98,
        name: "Californium",
        symbol: "Cf",
        roomTempState: ENUM.State.Solid,
        series: ENUM.Series.Actinoids,
        metal: ENUM.Metal.Metal,
        group: ENUM.Group.Actinoids,
        families: [],
        atomicMass: 251,
        electronegativity: 1.3,
        calculatedRadius: 245,
        electronAffinity: null,
        firstIonization: 608.0,
        period: 7,
        groupNum: null,
        block: ENUM.Block.F,
    },
    {
        atomicNumber: 99,
        name: "Einsteinium",
        symbol: "Es",
        roomTempState: ENUM.State.Solid,
        series: ENUM.Series.Actinoids,
        metal: ENUM.Metal.Metal,
        group: ENUM.Group.Actinoids,
        families: [],
        atomicMass: 252,
        electronegativity: 1.3,
        calculatedRadius: 245,
        electronAffinity: null,
        firstIonization: 619.0,
        period: 7,
        groupNum: null,
        block: ENUM.Block.F,
    },
    {
        atomicNumber: 100,
        name: "Fermium",
        symbol: "Fm",
        roomTempState: ENUM.State.Unknown,
        series: ENUM.Series.Actinoids,
        metal: ENUM.Metal.Metal,
        group: ENUM.Group.Actinoids,
        families: [],
        atomicMass: 257,
        electronegativity: 1.3,
        calculatedRadius: 245,
        electronAffinity: null,
        firstIonization: 627.0,
        period: 7,
        groupNum: null,
        block: ENUM.Block.F,
    },
    {
        atomicNumber: 101,
        name: "Mendelevium",
        symbol: "Md",
        roomTempState: ENUM.State.Unknown,
        series: ENUM.Series.Actinoids,
        metal: ENUM.Metal.Metal,
        group: ENUM.Group.Actinoids,
        families: [],
        atomicMass: 258,
        electronegativity: 1.3,
        calculatedRadius: 246,
        electronAffinity: null,
        firstIonization: 635.0,
        period: 7,
        groupNum: null,
        block: ENUM.Block.F,
    },
    {
        atomicNumber: 102,
        name: "Nobelium",
        symbol: "No",
        roomTempState: ENUM.State.Unknown,
        series: ENUM.Series.Actinoids,
        metal: ENUM.Metal.Metal,
        group: ENUM.Group.Actinoids,
        families: [],
        atomicMass: 259,
        electronegativity: 1.3,
        calculatedRadius: 246,
        electronAffinity: null,
        firstIonization: 642.0,
        period: 7,
        groupNum: null,
        block: ENUM.Block.F,
    },
    {
        atomicNumber: 103,
        name: "Lawrencium",
        symbol: "Lr",
        roomTempState: ENUM.State.Unknown,
        series: ENUM.Series.Actinoids,
        metal: ENUM.Metal.Metal,
        group: ENUM.Group.Actinoids,
        families: [],
        atomicMass: 262,
        electronegativity: 1.3,
        calculatedRadius: 246,
        electronAffinity: null,
        firstIonization: 470.0,
        period: 7,
        groupNum: null,
        block: ENUM.Block.F,
    },
    {
        atomicNumber: 104,
        name: "Rutherfordium",
        symbol: "Rf",
        roomTempState: ENUM.State.Unknown,
        series: ENUM.Series.TransitionMetals,
        metal: ENUM.Metal.Metal,
        group: ENUM.Group.Transition,
        families: [],
        atomicMass: 267,
        electronegativity: null,
        calculatedRadius: null,
        electronAffinity: null,
        firstIonization: 580.0,
        period: 7,
        groupNum: 4,
        block: ENUM.Block.D,
    },
    {
        atomicNumber: 105,
        name: "Dubnium",
        symbol: "Db",
        roomTempState: ENUM.State.Unknown,
        series: ENUM.Series.TransitionMetals,
        metal: ENUM.Metal.Metal,
        group: ENUM.Group.Transition,
        families: [],
        atomicMass: 268,
        electronegativity: null,
        calculatedRadius: null,
        electronAffinity: null,
        firstIonization: null,
        period: 7,
        groupNum: 5,
        block: ENUM.Block.D,
    },
    {
        atomicNumber: 106,
        name: "Seaborgium",
        symbol: "Sg",
        roomTempState: ENUM.State.Unknown,
        series: ENUM.Series.TransitionMetals,
        metal: ENUM.Metal.Metal,
        group: ENUM.Group.Transition,
        families: [],
        atomicMass: 271,
        electronegativity: null,
        calculatedRadius: null,
        electronAffinity: null,
        firstIonization: null,
        period: 7,
        groupNum: 6,
        block: ENUM.Block.D,
    },
    {
        atomicNumber: 107,
        name: "Bohrium",
        symbol: "Bh",
        roomTempState: ENUM.State.Unknown,
        series: ENUM.Series.TransitionMetals,
        metal: ENUM.Metal.Metal,
        group: ENUM.Group.Transition,
        families: [],
        atomicMass: 272,
        electronegativity: null,
        calculatedRadius: null,
        electronAffinity: null,
        firstIonization: null,
        period: 7,
        groupNum: 7,
        block: ENUM.Block.D,
    },
    {
        atomicNumber: 108,
        name: "Hassium",
        symbol: "Hs",
        roomTempState: ENUM.State.Unknown,
        series: ENUM.Series.TransitionMetals,
        metal: ENUM.Metal.Metal,
        group: ENUM.Group.Transition,
        families: [],
        atomicMass: 270,
        electronegativity: null,
        calculatedRadius: null,
        electronAffinity: null,
        firstIonization: null,
        period: 7,
        groupNum: 8,
        block: ENUM.Block.D,
    },
    {
        atomicNumber: 109,
        name: "Meitnerium",
        symbol: "Mt",
        roomTempState: ENUM.State.Unknown,
        series: ENUM.Series.TransitionMetals,
        metal: ENUM.Metal.Metal,
        group: ENUM.Group.Transition,
        families: [],
        atomicMass: 276,
        electronegativity: null,
        calculatedRadius: null,
        electronAffinity: null,
        firstIonization: null,
        period: 7,
        groupNum: 9,
        block: ENUM.Block.D,
    },
    {
        atomicNumber: 110,
        name: "Darmstadtium",
        symbol: "Ds",
        roomTempState: ENUM.State.Unknown,
        series: ENUM.Series.TransitionMetals,
        metal: ENUM.Metal.Metal,
        group: ENUM.Group.Transition,
        families: [],
        atomicMass: 281,
        electronegativity: null,
        calculatedRadius: null,
        electronAffinity: null,
        firstIonization: null,
        period: 7,
        groupNum: 10,
        block: ENUM.Block.D,
    },
    {
        atomicNumber: 111,
        name: "Roentgenium",
        symbol: "Rg",
        roomTempState: ENUM.State.Unknown,
        series: ENUM.Series.TransitionMetals,
        metal: ENUM.Metal.Metal,
        group: ENUM.Group.Transition,
        families: [],
        atomicMass: 280,
        electronegativity: null,
        calculatedRadius: null,
        electronAffinity: null,
        firstIonization: null,
        period: 7,
        groupNum: 11,
        block: ENUM.Block.D,
    },
    {
        atomicNumber: 112,
        name: "Copernicium",
        symbol: "Cn",
        roomTempState: ENUM.State.Unknown,
        series: ENUM.Series.TransitionMetals,
        metal: ENUM.Metal.Metal,
        group: ENUM.Group.Transition,
        families: [],
        atomicMass: 285,
        electronegativity: null,
        calculatedRadius: null,
        electronAffinity: null,
        firstIonization: null,
        period: 7,
        groupNum: 12,
        block: ENUM.Block.D,
    },
    {
        atomicNumber: 113,
        name: "Nihonium",
        symbol: "Nh",
        roomTempState: ENUM.State.Unknown,
        series: ENUM.Series.PostTransitionMetals,
        metal: ENUM.Metal.Metal,
        group: ENUM.Group.Triels,
        families: [],
        atomicMass: 284,
        electronegativity: null,
        calculatedRadius: null,
        electronAffinity: null,
        firstIonization: null,
        period: 7,
        groupNum: 13,
        block: ENUM.Block.P,
    },
    {
        atomicNumber: 114,
        name: "Flerovium",
        symbol: "Fl",
        roomTempState: ENUM.State.Unknown,
        series: ENUM.Series.PostTransitionMetals,
        metal: ENUM.Metal.Metal,
        group: ENUM.Group.Tetrels,
        families: [],
        atomicMass: 289,
        electronegativity: null,
        calculatedRadius: null,
        electronAffinity: null,
        firstIonization: null,
        period: 7,
        groupNum: 14,
        block: ENUM.Block.P,
    },
    {
        atomicNumber: 115,
        name: "Moscovium",
        symbol: "Mc",
        roomTempState: ENUM.State.Unknown,
        series: ENUM.Series.PostTransitionMetals,
        metal: ENUM.Metal.Metal,
        group: ENUM.Group.Pnictogens,
        families: [],
        atomicMass: 288,
        electronegativity: null,
        calculatedRadius: null,
        electronAffinity: null,
        firstIonization: null,
        period: 7,
        groupNum: 15,
        block: ENUM.Block.P,
    },
    {
        atomicNumber: 116,
        name: "Livermorium",
        symbol: "Lv",
        roomTempState: ENUM.State.Unknown,
        series: ENUM.Series.PostTransitionMetals,
        metal: ENUM.Metal.Metal,
        group: ENUM.Group.Chalcogens,
        families: [],
        atomicMass: 293,
        electronegativity: null,
        calculatedRadius: null,
        electronAffinity: null,
        firstIonization: null,
        period: 7,
        groupNum: 16,
        block: ENUM.Block.P,
    },
    {
        atomicNumber: 117,
        name: "Tennessine",
        symbol: "Ts",
        roomTempState: ENUM.State.Unknown,
        series: ENUM.Series.PostTransitionMetals,
        metal: ENUM.Metal.Metal,
        group: ENUM.Group.Halogens,
        families: [],
        atomicMass: 294,
        electronegativity: null,
        calculatedRadius: null,
        electronAffinity: null,
        firstIonization: null,
        period: 7,
        groupNum: 17,
        block: ENUM.Block.P,
    },
    {
        atomicNumber: 118,
        name: "Oganesson",
        symbol: "Og",
        roomTempState: ENUM.State.Unknown,
        series: ENUM.Series.NobleGases,
        metal: ENUM.Metal.Nonmetal,
        group: ENUM.Group.NobleGasses,
        families: [],
        atomicMass: 294,
        electronegativity: null,
        calculatedRadius: null,
        electronAffinity: null,
        firstIonization: null,
        period: 7,
        groupNum: 18,
        block: ENUM.Block.P,
    },
];

export { compareEnums, ENUM, elements };